#  \##|   |
###\\ |   |
#   \\|   \'---'/   Dante (@koalagang)
#    \   _'.'O'.'   https://github.com/koalagang
#     | :___   \
#     |  _| :  |
#     | :__,___/
#     |   |
#     |   |
#
# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html
#
# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Keybindings for normal mode
config.bind('M', 'hint links spawn mpv {hint-url}')
config.bind('Z', 'hint links spawn alacritty -e youtube-dl {hint-url}')
config.bind('ss', 'config-cycle statusbar.show always never;; config-cycle tabs.show always never')
config.bind('T', 'config-cycle tabs.show always never')
config.bind('d', 'scroll-page 0 1')
config.bind('u', 'scroll-page 0 -1')

# Aliases
c.aliases = {'q': 'quit', 'w': 'session-save', 'wq': 'quit --save'}

#---Limits & Delays
c.completion.height = 200
c.completion.shrink = True
c.completion.scrollbar.width = 10
c.content.cache.maximum_pages = 50
c.keyhint.delay = 0
c.messages.timeout = 5000
c.tabs.show_switching_delay = 1500

#---Appearance & Functionality
c.url.searchengines = {'DEFAULT': 'https://duckduckgo.com/?q={}', 'w': 'http://en.wikipedia.org/w/index.php?search={}', 'aw': 'https://wiki.archlinux.org/?search={}', 'c': "https://www.collinsdictionary.com/dictionary/english/{}", 'gh': 'https://github.com/search?q={}', 'y': 'https://www.youtube.com/results?search_query=test&page&utm_source=opensearch{}', 'gt': 'https://translate.google.com/?source=osdd#auto|auto|{}'}
c.search.ignore_case = "always"
c.statusbar.show = "in-mode"
c.tabs.close_mouse_button = "right"
c.tabs.last_close = "close"
c.tabs.show = "switching"
c.tabs.mode_on_change = "restore"
c.statusbar.widgets = ['url', 'keypress', 'progress']
c.input.insert_mode.auto_load = True
c.scrolling.smooth = True
c.input.spatial_navigation = True
#c.downloads.remove_finished = -1
#config.set('fileselect.multiple_files.command', 'alacritty', '-e','vifm','--choosefiles=()')
#config.set('fileselect.single_file.command', 'alacritty', '-e','vifm','--choosefile=()')
#c.tabs.title.format =
c.window.hide_decoration = True

#---Privacy & Security

c.content.javascript.enabled  = False
c.content.headers.do_not_track = True
config.set('content.cookies.accept', 'no-3rdparty', 'devtools://*')
config.set('content.cookies.accept', 'no-3rdparty', 'chrome-devtools://*')
c.content.private_browsing = True
c.new_instance_open_target = "private-window"
c.downloads.location.prompt = False
c.downloads.location.directory = "~/Downloads"
c.content.geolocation = False
c.content.media.audio_capture = False
c.content.media.video_capture = False
c.content.media.audio_video_capture = False
c.content.notifications = False
c.content.autoplay = False
c.content.canvas_reading = False
c.content.dns_prefetch = False
c.content.headers.referer = "same-domain"
c.content.mouse_lock = False
#c.content.proxy =
#c.content.proxy_dns_requests =
c.content.webgl = False
c.content.webrtc_ip_handling_policy = "default-public-interface-only"
#c.ssl_strict = "ask"
#c.content.unknown_url_scheme_policy = "allow-from-user-interaction"
#
# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
#config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')
#config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version} Edg/{upstream_browser_version}', 'https://accounts.google.com/*')
#config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36', 'https://*.slack.com/*')
#
# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')
config.set('content.images', True, 'devtools://*')
#
# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')
config.set('content.javascript.enabled', True, 'devtools://*')
config.set('content.javascript.enabled', True, 'chrome://*/*')
config.set('content.javascript.enabled', True, 'qute://*/*')
