#!/bin/sh
# Any functions I don't actually use are commented out.

# File/folder extraction
ex (){
    if [ -f "$1" ] ; then
        case "$1" in
            *.tar.bz2)   tar xjf "$1"    ;;
            *.tar.gz)    tar xf "$1"     ;;
            *.bz2)       bunzip2 "$1"    ;;
            *.rar)       unrar x "$1"    ;;
            *.gz)        gunzip "$1"     ;;
            *.tar)       tar xf "$1"     ;;
            *.tbz2)      tar xjf "$1"    ;;
            *.tgz)       tar xzf "$1"    ;;
            *.zip)       unzip "$1"      ;;
            *.Z)         uncompress "$1" ;;
            *.7z)        7z x "$1"       ;;
            *.deb)       ar x "$1"       ;;
            *.tar.xz)    tar xf "$1"     ;;
            *.tar.zst)   unzstd "$1"     ;;
            *)           echo "'$1' cannot be extracted with ex"
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# File/folder compression
comp (){
    case "$2" in
        '-t')   tar -c --auto-compress -f "$1.tar.gz" "$1" ;;
        '-z')   tar -c --auto-compress -f "$1.zip" "$1" ;;
        '-d')   tar -c --auto-compress -f "$1.deb" "$1" ;;
        *)      tar -c --auto-compress -f "$1.tar.gz" "$1"
    esac
}

# Use vifm to switch directories
#vifmcd () {
#    tmp="$(mktemp)"
#    vifm --choose-dir="$tmp" "$@" --select $(pwd)
#    [ -f "$tmp" ] && dir="$(cat "$tmp")" && rm -f "$tmp" ; [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
#}
#bindkey -s '^o' 'vifmcd\n'

xcp (){ # Copy files to clipboard (using xclip)
    case "$1" in
        *.jpeg) xclip -selection clipboard -target image/jpeg "$1" ;;
        *.jpg)  xclip -selection clipboard -target image/jpg "$1" ;;
        *.png)  xclip -selection clipboard -target image/png "$1" ;;
        *.bpm)  xclip -selection clipboard -target image/bpm "$1" ;;
        *.xpm)  xclip -selection clipboard -target image/xpm "$1" ;;
        *.gif)  xclip -selection clipboard -target image/gif "$1" ;;
        *)      xclip -selection clipboard "$1"
    esac
}

#dictd () { # Query dict.org for a word defintion
#    curl --silent dict://dict.org/d:$1 | less
#}

bak () { # Backup a file
    cp --backup=numbered "$1" "$1.bak"
}

oxo (){ # Upload content to 0x0.st
while getopts 's:f:u:' OPT; do
  case $OPT in
    s) curl -F "shorten=$OPTARG" http://0x0.st ;;
    f) curl -F "file=@$OPTARG" http://0x0.st   ;;
    u) curl -F "url=$OPTARG" http://0x0.st     ;;
    *) echo 'error: invalid flag'
  esac
done
}

# TOOD: configure filename formatting
ytdl (){
    # swap `yt-dlp` out for `yotube-dl` if you prefer that
    yt-dlp "$1" --external-downloader 'axel' --external-downloader-args '-n 10'
}
