#!/bin/bash
inputFile="$( echo $1 | sed 's!~!\/home\/admin!')"
[ -z "$inputFile" ] && exit
dir=$(dirname "$inputFile")

case "$inputFile" in 

	*c)
		cd "$dir"
		name="$(echo $inputFile | sed 's/\..*//')"
		gcc "$inputFile" -o "$name"
		;;

	*config.h)
		cd "$dir"
		sudo make clean install
		;;
	*tex)
		cd "$dir"
		pdflatex "$inputFile"
		;;
	
	*ms)
		eqn="$(grep "\.EQ" -i $inputFile | head -1)"
		name="$(echo $inputFile | sed 's/\..*//')"
		cd "$dir"
		[ -z "$eqn" ] || {
		       	groff -e -t "$inputFile" -ms -Tpdf > "$name.pdf" && exit
		}
		groff -t -ms "$inputFile" -Tpdf > "$name.pdf" 
		;;
esac
