#!/bin/sh

while true; do
    printf '1. dwm\n2. openbox\n'
    read -p 'Select an environment: ' env
    case "$env" in
        1) WM='dwm' ; break ;;
        2) WM='openbox' ; break ;;
        *) echo 'Please select one of the options (answer with a number).'
    esac
done

export WM

startx "$XDG_CONFIG_HOME/X11/xinitrc"
