#!/bin/sh

# xinitrc runs automatically when you run `startx "$HOME/.config/X11/xinitrc"`

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

#if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ]; then
#	. "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile"
#else
#	. "$HOME/.xprofile"
#fi

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" && exit 0

. "$HOME/.xprofile"
