#!/bin/sh

pipewire &
pipewire-pulse &
wireplumber &

xcompmgr &
sxhkd &
dunst &
unclutter --timeout 3 &
dwmblocks &

HOST_NAME="$(</etc/hostname)"
if [ "$HOST_NAME" = 'Ljosalfheim' ]; then
    xrandr --ouput HDMI-0 --mode 1920x1080 --output HDMI-1-1 --mode 1920x1080 --left-of HDMI-0
    nvffcp
elif [ "$HOST_NAME" = 'Svartalfheim' ]; then
    xrandr --output LVDS1 --mode 1366x768
fi
xrdb "$XDG_CONFIG_HOME/X11/xresources"
redshift -O 2500K
xwallpaper --focus "$XDG_DATA_HOME/wall.jpg"
kbd-remaps

exec "$wm"
