#!/bin/sh
# AUTHOR: koalagang (https://github.com/koalagang)
# Dependencies: jq, $searcher and $menu (see options below)

### OPTIONS ###

# you can easily swap $searcher out with googler if you prefer that
searcher='ddgr'
#searcher='googler'

menu='dmenu'
#menu='rofi -dmenu'
#menu='bemenu'

###############

# take user input for what to search and place it in a variable
query="$(printf '' | $menu -p 'Search: ')" || exit 0 # exit if the user hits escape
[ -z "$query" ] && exit 0 # exit if the user hits enter/return without inputting any text

# lookup the contents of $query and give the user the first 20 available options
# also store the json file for later use
# shellcheck disable=SC1003
choice="$($searcher "$query" --json -n 20 | tee '/tmp/ddgmenu.json' | jq '.[].title' | tr -d '\\' | $menu -l 20)"
# remove the first and last quotation mark
choice2=${choice#'"'}
choice2=${choice2%'"'}

# search ddgmenu.json for a title containing the contents of $choice2, grab the URL and then open it in the browser
jq --arg choice "$choice2" '.[] | select(.title==$choice)' '/tmp/ddgmenu.json' | jq '.url' | xargs "$BROWSER"

# cleanup
rm '/tmp/ddgmenu.json'
