#!/bin/sh

# AUTHOR: koalagang (https://github.com/koalagang)
# Dependencies: wget
# Give the script a link to a bibtex file and downloadbib will download it and place it in your .bib file
# (provided that you have assigned $BIB to it in your environmental variables file).

download_bib="$XDG_CACHE_HOME/downloadbib.txt"
[ -n "$1" ] && url="$1"
[ -z "$1" ] && url="$(xclip -sel c -o)"

wget robots=off -U mozilla "$url" -O "$download_bib"
tag="$(grep '@' "$download_bib")"
tag="${tag##*\{}"

if [ "$(grep 'author' "$download_bib" | tr -d '[:alnum:]={}.' | wc -w)" -eq 1 ]; then
    author="$(awk '/author/ {print $NF}' "$download_bib" | cut -d'}' -f1)"
elif [ "$(grep 'author' "$download_bib" | tr -d '[:alnum:]={}' | wc -w)" -eq 2 ]; then
    author="$(grep 'author' "$download_bib" | sed 's/.*{\(.*\)}/\1/' | cut -d',' -f1)"
else
    echo 'This must be handled manually.'
fi
year="$(awk -F '{' '/year/ {print $2}' "$download_bib" | cut -d'}' -f1)"

sed -i "s#$tag#$author-$year,#" "$download_bib"
echo >> "$BIB"
cat "$download_bib" >> "$BIB"
rm "$download_bib"
