#!/bin/sh

# AUTHOR: koalagang (https://github.com/koalagang)
# Dependencies: legendary, dmenu, a browser (optional - for opening the Epic Games free games page; the default is Brave)
# A dmenu script for using Epic Games on Linux.

# Browser to use for getting the freebies from Epic Games' website
webbrowser="$BROWSER"
games_path="$HOME/.local/share/games/legendary"

find_game () {
    game="$(legendary "list-$list" | sed -e '/games/d' -e '/^$/d' -e '/Total/d' | tr -d '*' | dmenu -i -l 20)" || exit 0
    app_name="$(echo "$game" | grep -oP '\(\K[^\)]+' | cut -d' ' -f3)"
}

case "$(printf "Launch a game\nInstall a game\nUninstall a game\nDownload all cloud saves\nSync cloud saves\nGet freebies" | dmenu -i -p 'Epic Games')" in
    'Launch a game') list="installed" && find_game && legendary launch "$app_name" ;;
    'Install a game') notify-send "Epic Games" "Logging in" && list="games" && find_game && notify-send "Epic Games" "Installing game." &&
        legendary install "$app_name" -y && notify-send "Epic Games" "Game finished installing." ;;
    'Uninstall a game') list="installed" && find_game && notify-send "Epic Games" "Uninstalling game." &&
        legendary uninstall "$app_name" -y && notify-send "Epic Games" "Game finished uninstalling." ;;
    'Download all cloud saves') notify-send "Epic Games" "Downloading cloud saves." && legendary download-saves && \
        notify-send "Epic Games" "Cloud saves finished downlading." ;;
    'Sync cloud saves') notify-send "Epic Games" "Syncing cloud saves." && legendary sync-saves && \
        notify-send "Epic Games" "Cloud saves finished syncing." ;;
    'Get freebies') $webbrowser "https://www.epicgames.com/store/en-US/free-games"
esac

# TODO: add error message if fails to login
