#!/bin/sh
[ -z "$1" ] && echo "Give either PDF file, a DOI or an ISBN as an argument." && exit

if [ -f "$1" ]; then
    # Try to get DOI from pdfinfo or pdftotext output.
    doi="$(pdfinfo "$1" | grep -io "doi:.*")" ||
    doi="$(pdftotext "$1" 2>/dev/null - | grep -io "doi:.*" -m 1)" ||
    exit 1
else
    doi="$1"
fi

# Check crossref.org for the bib citation.
# TODO: automatically reformat citation
curl -s "https://api.crossref.org/works/$doi/transform/application/x-bibtex" -w "\\n" >> "$BIB"
#curl -s "https://lead.to/amazon/com/dl-bib-com.html?key=$isbn" -w "\\n" >> "$BIB" # isbn
