#!/bin/sh
# AUTHOR: koalagang (https://github.com/koalagang)
# Dependencies: firefox (I personally use ESR, you'd have to change it below if you don't use that), xdotool, bc, wmctrl
# I wrote and use this script because I like to use Firefox in fullscreen mode (use the auto fullscreen add-on)
# and I have to click onto the page just once initially to enable fullscreen.
# I don't use the bookmark bar because I use my own script (bookmenu).
# I also do not use the URL bar because I like using the vomnibar offered by the Vimium add-on.
# If you want to do the same, make sure that your homepage and newtab page are non-protected pages (because auto fullscreen can't be used on protected pages).
# I use about:blank as mine.

firefox-esr --profile "$HOME/.mozilla/firefox"/*.default & # launch Firefox
# sleep until Firefox has loaded up
while [ -z "$(echo "ibase=16; $(wmctrl -l | grep 'Mozilla Firefox' | cut -c 3-11 | tr a-z A-Z)" | bc)" ]; do
    sleep 0.1
done
# click on the coordinates (150,150) on Firefox
xdotool mousemove -w "$(echo "ibase=16; $(wmctrl -l | grep 'Mozilla Firefox' | cut -c 3-11 | tr a-z A-Z)" | bc)" 150 150 click 1
# The whole long echo command is there to find the window ID of Firefox for xdotool to know what window to click on.
