#!/bin/sh

# AUTHOR: koalagang
# This script simply serves the function of allowing me to use the same swhkd file on both dwm and dwl

# Wayland
if [ -n "$WAYLAND_DISPLAY" ]; then
    case "$1" in
        'lock') waylock ;;
        'terminal') footclient ;;
        'menu') bemenu-run ;;
        'signal') signal-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland ;;
        'blocks') echo 'someblocks'
    esac
# X11
else
    case "$1" in
        'lock') slock ;;
        'terminal') st ;;
        'menu') dmenu_run ;;
        'signal') signal-desktop ;;
        'blocks') echo 'dwmblocks'
    esac
fi
